######################################################################
# Automatically generated by qmake (3.0) Sun Sep 28 22:07:55 2014
######################################################################

TEMPLATE = app
TARGET = StructureSynth
INCLUDEPATH += .
INCLUDEPATH += .

# Input
HEADERS += resource.h \
           StructureSynth/GUI/MainWindow.h \
           StructureSynth/GUI/TemplateExportDialog.h \
           StructureSynth/GUI/VariableEditor.h \
           StructureSynth/JavaScriptSupport/Debug.h \
           StructureSynth/JavaScriptSupport/JavaScriptBuilder.h \
           StructureSynth/JavaScriptSupport/JavaScriptParser.h \
           StructureSynth/Model/Action.h \
           StructureSynth/Model/AmbiguousRule.h \
           StructureSynth/Model/Builder.h \
           StructureSynth/Model/ColorPool.h \
           StructureSynth/Model/CustomRule.h \
           StructureSynth/Model/ExecutionStack.h \
           StructureSynth/Model/PrimitiveClass.h \
           StructureSynth/Model/PrimitiveRule.h \
           StructureSynth/Model/RandomStreams.h \
           StructureSynth/Model/Rule.h \
           StructureSynth/Model/RuleRef.h \
           StructureSynth/Model/RuleSet.h \
           StructureSynth/Model/State.h \
           StructureSynth/Model/Transformation.h \
           StructureSynth/Model/TransformationLoop.h \
           StructureSynth/Parser/EisenParser.h \
           StructureSynth/Parser/Preprocessor.h \
           StructureSynth/Parser/Tokenizer.h \
           SyntopiaCore/Exceptions/Exception.h \
           SyntopiaCore/GLEngine/Box.h \
           SyntopiaCore/GLEngine/Dot.h \
           SyntopiaCore/GLEngine/EngineWidget.h \
           SyntopiaCore/GLEngine/Grid.h \
           SyntopiaCore/GLEngine/Line.h \
           SyntopiaCore/GLEngine/Mesh.h \
           SyntopiaCore/GLEngine/Object3D.h \
           SyntopiaCore/GLEngine/RaytraceTriangle.h \
           SyntopiaCore/GLEngine/Sphere.h \
           SyntopiaCore/GLEngine/Triangle.h \
           SyntopiaCore/Logging/ListWidgetLogger.h \
           SyntopiaCore/Logging/Logging.h \
           SyntopiaCore/Math/Matrix4.h \
           SyntopiaCore/Math/Random.h \
           SyntopiaCore/Math/Vector3.h \
           SyntopiaCore/Misc/ColorUtils.h \
           SyntopiaCore/Misc/MiniParser.h \
           SyntopiaCore/Misc/Persistence.h \
           SyntopiaCore/Misc/Version.h \
           ThirdPartyCode/MersenneTwister/MersenneTwister.h \
           StructureSynth/Model/Rendering/ObjRenderer.h \
           StructureSynth/Model/Rendering/OpenGLRenderer.h \
           StructureSynth/Model/Rendering/Renderer.h \
           StructureSynth/Model/Rendering/TemplateRenderer.h \
           SyntopiaCore/GLEngine/Raytracer/AtomicCounter.h \
           SyntopiaCore/GLEngine/Raytracer/ProgressiveOutput.h \
           SyntopiaCore/GLEngine/Raytracer/RayTracer.h \
           SyntopiaCore/GLEngine/Raytracer/RenderThread.h \
           SyntopiaCore/GLEngine/Raytracer/Sampler.h \
           SyntopiaCore/GLEngine/Raytracer/VoxelStepper.h
SOURCES += Main.cpp \
           StructureSynth/GUI/MainWindow.cpp \
           StructureSynth/GUI/TemplateExportDialog.cpp \
           StructureSynth/GUI/VariableEditor.cpp \
           StructureSynth/JavaScriptSupport/Debug.cpp \
           StructureSynth/JavaScriptSupport/JavaScriptBuilder.cpp \
           StructureSynth/JavaScriptSupport/JavaScriptParser.cpp \
           StructureSynth/Model/Action.cpp \
           StructureSynth/Model/AmbiguousRule.cpp \
           StructureSynth/Model/Builder.cpp \
           StructureSynth/Model/ColorPool.cpp \
           StructureSynth/Model/CustomRule.cpp \
           StructureSynth/Model/ExecutionStack.cpp \
           StructureSynth/Model/PrimitiveClass.cpp \
           StructureSynth/Model/PrimitiveRule.cpp \
           StructureSynth/Model/RandomStreams.cpp \
           StructureSynth/Model/Rule.cpp \
           StructureSynth/Model/RuleRef.cpp \
           StructureSynth/Model/RuleSet.cpp \
           StructureSynth/Model/State.cpp \
           StructureSynth/Model/Transformation.cpp \
           StructureSynth/Model/TransformationLoop.cpp \
           StructureSynth/Parser/EisenParser.cpp \
           StructureSynth/Parser/Preprocessor.cpp \
           StructureSynth/Parser/Tokenizer.cpp \
           SyntopiaCore/GLEngine/Box.cpp \
           SyntopiaCore/GLEngine/Dot.cpp \
           SyntopiaCore/GLEngine/EngineWidget.cpp \
           SyntopiaCore/GLEngine/Grid.cpp \
           SyntopiaCore/GLEngine/Line.cpp \
           SyntopiaCore/GLEngine/Mesh.cpp \
           SyntopiaCore/GLEngine/Object3D.cpp \
           SyntopiaCore/GLEngine/RaytraceTriangle.cpp \
           SyntopiaCore/GLEngine/Sphere.cpp \
           SyntopiaCore/GLEngine/Triangle.cpp \
           SyntopiaCore/Logging/ListWidgetLogger.cpp \
           SyntopiaCore/Logging/Logging.cpp \
           SyntopiaCore/Math/Matrix4.cpp \
           SyntopiaCore/Math/Random.cpp \
           SyntopiaCore/Math/Vector3.cpp \
           SyntopiaCore/Misc/ColorUtils.cpp \
           SyntopiaCore/Misc/MiniParser.cpp \
           SyntopiaCore/Misc/Persistence.cpp \
           SyntopiaCore/Misc/Version.cpp \
           StructureSynth/Model/Rendering/ObjRenderer.cpp \
           StructureSynth/Model/Rendering/OpenGLRenderer.cpp \
           StructureSynth/Model/Rendering/Renderer.cpp \
           StructureSynth/Model/Rendering/TemplateRenderer.cpp \
           SyntopiaCore/GLEngine/Raytracer/AtomicCounter.cpp \
           SyntopiaCore/GLEngine/Raytracer/RayTracer.cpp \
           SyntopiaCore/GLEngine/Raytracer/RenderThread.cpp \
           SyntopiaCore/GLEngine/Raytracer/Sampler.cpp \
           SyntopiaCore/GLEngine/Raytracer/VoxelStepper.cpp
RESOURCES += StructureSynth.qrc
CONFIG+=opengl widgets
QT+=xml opengl script widgets


win32-msvc2008|win32-msvc2010|win64-msvc2013|win32-msvc2013 {
        # Enable Level 4 compiler warnings
       # QMAKE_CXXFLAGS_WARN_ON -= -W3
       # QMAKE_CXXFLAGS_WARN_ON += -W4
        # Hush some known Qt warnings
        QMAKE_CXXFLAGS += -wd4127 -wd4512 -wd4189 -wd4996
}


unix|win32: LIBS += -L$$PWD/../../freeglut-MSVC-2.8.1-1.mp/freeglut/lib/ -lfreeglut

INCLUDEPATH += $$PWD/../../freeglut-MSVC-2.8.1-1.mp/freeglut/include/GL
DEPENDPATH += $$PWD/../../freeglut-MSVC-2.8.1-1.mp/freeglut/include/GL

win32:!win32-g++: PRE_TARGETDEPS += $$PWD/../../freeglut-MSVC-2.8.1-1.mp/freeglut/lib/freeglut.lib
else:unix|win32-g++: PRE_TARGETDEPS += $$PWD/../../freeglut-MSVC-2.8.1-1.mp/freeglut/lib/libfreeglut.a
